name: techno_switch_rhino_103_controller
description: A new Flutter project for reading event logs from Techno Switch Rhino 103 controller.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  usb_serial: ^0.5.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
